name: Deploy to NuGet

on:
  push:
    tags:
      - "v*"
env:
  PROJECT_PATH: "src/Sork.Funk.csproj"
  PACKAGE_OUTPUT_DIRECTORY: ${{ github.workspace }}/output
  NUGET_SOURCE_URL: "https://api.nuget.org/v3/index.json"
  NUGET_AUTH_TOKEN: ${{ secrets.NUGET_TOKEN }}

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET 8
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.x.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore --configuration Release
      
    - name: Get version from Git tags
      id: get_version
      run: |
        VERSION=$(git describe --tags --abbrev=0)
        VERSION_WITHOUT_V=${VERSION#v}
        echo "VERSION=$VERSION_WITHOUT_V" >> $GITHUB_ENV

    - name: "Pack project"
      run: dotnet pack ${{ env.PROJECT_PATH }} --no-restore --no-build --configuration Release -p:PackageVersion=${{ env.VERSION }} --output ${{ env.PACKAGE_OUTPUT_DIRECTORY }}

    - name: "Push package"
      run: dotnet nuget push ${{ env.PACKAGE_OUTPUT_DIRECTORY }}/*.nupkg -k ${{ env.NUGET_AUTH_TOKEN }} -s ${{ env.NUGET_SOURCE_URL }}
